# Generated by Django 5.1.5 on 2025-01-25 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Sobrenome"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("BR", "Brasileiro"),
                            ("PT", "Português"),
                            ("GB", "Guineense"),
                            ("SN", "Senegalense"),
                            ("OT", "Outro"),
                        ],
                        default="OT",
                        max_length=2,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Telefone"),
                ),
                ("email", models.EmailField(max_length=260, verbose_name="Email")),
                ("address", models.TextField(verbose_name="Endereço")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Código Postal"),
                ),
                (
                    "student_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Número do Aluno",
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_images",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parents.parent",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
