# Generated by Django 5.1.5 on 2025-01-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="user",
            new_name="usuario",
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="student_profile_images",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
