# Generated by Django 5.1.5 on 2025-01-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Sala")),
                ("capacity", models.PositiveIntegerField(verbose_name="Capacidade")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Localização da Sala",
                    ),
                ),
                (
                    "classes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes",
                        to="classes.class",
                        verbose_name="Sala de Aula",
                    ),
                ),
            ],
        ),
    ]
