# Generated by Django 5.1.5 on 2025-01-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="classes",
        ),
    ]
