# Generated by Django 5.1.5 on 2025-01-25 13:55

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da Turma"),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=9,
                        validators=[classes.models.validate_year_format],
                        verbose_name="Ano Letivo",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("morning", "Manhã"),
                            ("afternoon", "Tarde"),
                            ("evening", "Noite"),
                        ],
                        max_length=10,
                        verbose_name="Período",
                    ),
                ),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade de Alunos"
                    ),
                ),
            ],
        ),
    ]
