# Generated by Django 5.1.5 on 2025-01-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("rooms", "0002_remove_room_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="rooms.room",
                verbose_name="Sala de Aula",
            ),
        ),
    ]
